server:
  port: 8085

spring:
  application:
    name: eventosproxy

  security:
    authentication:
      jwt:
        base64-secret: cG8tbXktc2VjcmV0LWFwcA==
        token-validity-in-seconds: 86400

  docker:
    compose:
      enabled: false

  main:
    web-application-type: servlet

  cloud:
    stream:
      enabled: false
    function:
      definition: none

management:
  endpoints:
    web:
      exposure:
        include: "*"

jhipster:
  clientApp:
    name: eventosproxy
  security:
    authentication:
      jwt:
        base64-secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000

logging:
  level:
    root: INFO
    com.stefanopalazzo: DEBUG
