server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventos_db
    username: eventos_user
    password: eventos_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # durante desarrollo; m√°s adelante "validate"
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: 192.168.194.250:9092
    consumer:
      group-id: stefanopalazzo-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: "2c08c8f9dfe21ab87e7683123a518b9283743ffeb1c0f233bc12e8b9123aa239"
  expiration: 86400000   # 24h

catedra:
  base-url: http://192.168.194.250:8080/api/endpoints/v1
  auth-url: http://192.168.194.250:8080/api/authenticate
  agregar-usuario-url: http://192.168.194.250:8080/api/v1/agregar_usuario
  eventos-resumidos: ${catedra.base-url}/eventos-resumidos
  eventos-completos: ${catedra.base-url}/eventos
  evento-detalle: ${catedra.base-url}/evento
  bloquear-asientos: ${catedra.base-url}/bloquear-asientos
  realizar-venta: ${catedra.base-url}/realizar-venta
  listar-ventas: ${catedra.base-url}/listar-ventas
  listar-venta: ${catedra.base-url}/listar-venta
  username: admin
  password: admin
#  base-url: "https://prog2-events.azurewebsites.net"
