spring:
  kafka:
    bootstrap-servers: 192.168.194.250:9092
    consumer:
      group-id: stefanopalazzo-proxy-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

proxy:
  backend-url: http://eventos_backend:8081
  token: "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzdGVmYW5vcGFsYXp6b190ZXN0IiwiZXhwIjoxNzY4MDg4OTI0LCJhdXRoIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzY1NDk2OTI0fQ.OaVwxtYsFJ4f0LyesNrdZRQHsTHfSmVHWGHdsfAJvTY_LYCJHhtochoEIw0-F_nwY3TabfQoWU_C2pNUpSv7WA"
  chair-url: http://192.168.194.250:8080/api
  redis:
    host: 192.168.194.250
    port: 6379

