spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/eventos_db
    username: eventos_user
    password: eventos_pass
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
    redis:
      host: redis-local
      port: 6379
      namespace: spring:session
    timeout: 1800
  kafka:
    bootstrap-servers: kafka:9092

app:
  proxy-url: http://proxy:8085

jwt:
  secret: "2c08c8f9dfe21ab87e7683123a518b9283743ffeb1c0f233bc12e8b9123aa239"
  expiration: 8640000000

catedra:
  base-url: http://192.168.194.250:8080/api/endpoints/v1
  auth-url: http://192.168.194.250:8080/api/authenticate
  agregar-usuario-url: http://192.168.194.250:8080/api/v1/agregar_usuario
  eventos-resumidos: ${catedra.base-url}/eventos-resumidos
  eventos-completos: ${catedra.base-url}/eventos
  evento-detalle: ${catedra.base-url}/evento
  bloquear-asientos: ${catedra.base-url}/bloquear-asientos
  realizar-venta: ${catedra.base-url}/realizar-venta
  listar-ventas: ${catedra.base-url}/listar-ventas
  listar-venta: ${catedra.base-url}/listar-venta
  username: admin
  password: admin
